FROM centos:7

RUN yum update -y && \
    yum install -y httpd && \
    yum clean all

RUN echo "This is container ID: " > /var/www/html/index.html && \
    hostname >> /var/www/html/index.html

RUN useradd -u 1000 saman && \
    chown -R saman:saman /var/www/html && \
    chown -R saman:saman /var/log/httpd && \
    chown -R saman:saman /run/httpd

RUN chmod -R 740 /var/log/httpd && \
    chmod -R 740 /run/httpd && \
    setcap 'cap_net_bind_service=+ep' /usr/sbin/httpd

EXPOSE 80

USER saman

CMD ["/usr/sbin/httpd", "-D", "FOREGROUND"]
