version: '3'
services:
  web1:
    build:
      context: .
      dockerfile: Dockerfile-web
    container_name: ptc-web1
    restart: always
    networks:
      - samnet
  web2:
    build:
      context: .
      dockerfile: Dockerfile-web
    container_name: ptc-web2
    restart: always
    networks:
      - samnet
  loadbalancer:
    build:
      context: .
      dockerfile: Dockerfile-lb
    container_name: ptc-docker-task-lb
    restart: always
    networks:
      - samnet
    ports:
      - "80:80"
networks:
  samnet:
