FROM centos:7

RUN yum update -y && \
    yum install -y httpd && \
    yum clean all

RUN echo "This is container ID: $(cat /proc/self/cgroup | grep "docker" | sed s/\\//\\n/g | tail -1)" > /var/www/html/index.html

RUN useradd -u 1000 saman && \
    chown -R saman:saman /var/www/html

RUN chmod -R 777 /var/log/httpd && \
    chmod -R 777 /run/httpd && \
    usermod -u 1000 saman && \
    setcap 'cap_net_bind_service=+ep' /usr/sbin/httpd

EXPOSE 80

USER saman

CMD ["/usr/sbin/httpd", "-D", "FOREGROUND"]
